# Generated by Django 4.1.7 on 2023-02-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=30, verbose_name="Имя автора"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=30, verbose_name="Фамилия автора"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="image/", verbose_name="Фото автора"
                    ),
                ),
                (
                    "date_of_created",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "date_edited",
                    models.DateField(auto_now=True, verbose_name="Дата редактирования"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["lastname"],
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Описание"),
                ),
                (
                    "number_of_pages",
                    models.PositiveIntegerField(verbose_name="Количество страниц"),
                ),
                (
                    "number_of_books",
                    models.PositiveIntegerField(verbose_name="Количество книг"),
                ),
                (
                    "date_of_created",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "date_edited",
                    models.DateField(auto_now=True, verbose_name="Дата редактирования"),
                ),
                (
                    "authors",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=30, verbose_name="Имя читателя"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=30, verbose_name="Фамилия читателя"),
                ),
                (
                    "phone",
                    models.BigIntegerField(unique=True, verbose_name="Номер телефона"),
                ),
                (
                    "status_reader",
                    models.BooleanField(default=True, verbose_name="Статус"),
                ),
                (
                    "active_books",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="catalog.books"
                    ),
                ),
            ],
            options={
                "verbose_name": "Читатель",
                "verbose_name_plural": "Читатели",
            },
        ),
    ]
