# Generated by Django 4.1.7 on 2023-02-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="author",
        ),
        migrations.RemoveField(
            model_name="books",
            name="reader",
        ),
        migrations.AddField(
            model_name="author",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.books",
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="books",
            field=models.ManyToManyField(to="catalog.books"),
        ),
        migrations.AlterField(
            model_name="reader",
            name="active_books",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Книги на руках"
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="firstname",
            field=models.CharField(max_length=30, verbose_name="Имя читателя"),
        ),
        migrations.AlterField(
            model_name="reader",
            name="lastname",
            field=models.CharField(max_length=30, verbose_name="Фамилия читателя"),
        ),
    ]
